"""update author relationship

Revision ID: 0ce8b8d4287a
Revises: 4f2977a19cb7
Create Date: 2023-10-13 14:19:35.557281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce8b8d4287a'
down_revision: Union[str, None] = '4f2977a19cb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'authors', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'authors', type_='foreignkey')
    op.drop_column('authors', 'created_by')
    # ### end Alembic commands ###
