"""update book relationship

Revision ID: 3cf9c3c4f8d7
Revises: 0ce8b8d4287a
Create Date: 2023-10-14 16:08:01.485664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cf9c3c4f8d7'
down_revision: Union[str, None] = '0ce8b8d4287a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('books', sa.Column('updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'updated')
    op.drop_column('books', 'created')
    # ### end Alembic commands ###
