"""First migrations

Revision ID: 4547a7ddb1a1
Revises: 
Create Date: 2023-10-13 12:25:22.114913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4547a7ddb1a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('publish_year', sa.Integer(), nullable=True))
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('books', 'year')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('books', sa.Column('year', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('books', 'publish_year')
    # ### end Alembic commands ###
