"""update books relationship

Revision ID: 88f92e53702d
Revises: d46e24805b95
Create Date: 2023-10-17 17:16:04.930507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88f92e53702d'
down_revision: Union[str, None] = 'd46e24805b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'created_by')
    # ### end Alembic commands ###
