"""First migrations

Revision ID: d372af458884
Revises: 
Create Date: 2023-10-13 09:15:41.897701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd372af458884'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('password', sa.String(), nullable=False))
    op.drop_column('author', '_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('_password', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_column('author', 'password')
    # ### end Alembic commands ###
